name: farmers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: train-model
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add Model Summary to the report
          cml-publish model-summary.txt --md >> rreport.md

          # Add figure to the report
          cml-publish results.png --md >> report.md
          
          cml-send-comment report.md