name: cml-in-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v1
 
      - uses: iterative/setup-dvc@v1
 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}

        run: |
          pip install -r requirements.txt
          dvc repro

          cml tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
          
          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add Model Summary to the report
          echo '```' >> report.md
          echo >> report.md
          cat model-summary.txt >> report.md
          echo '```' >> report.md
          echo >> report.md

          cml publish results.png --md >> report.md
          cml send-comment report.md