name: cml-in-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add Model Summary to the report
          cat model-summary.txt >> report.md

          cml publish results.png --md >> report.md
          cml send-comment report.md
